{"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":23522,"status":"ok","timestamp":1695750089313,"user":{"displayName":"sam Chain","userId":"00779398991030525753"},"user_tz":-120},"id":"BcuLdi7seAKr","outputId":"a57ae5af-106b-43d0-9d5a-816d53a8a4ca"},"outputs":[],"source":["import os\n","import pandas as pd\n","import tensorflow as tf\n","import numpy as np\n","import polars as pl\n","import nfl_data_py as nfl\n","\n","env = \"local\""]},{"cell_type":"code","execution_count":2,"metadata":{},"outputs":[],"source":["if env == \"local\":\n","    os.chdir(\"/Users/samuel/Documents/GitHub/QB-GPT/\")\n","else:\n","    from google.colab import drive\n","    drive.mount('/content/gdrive')\n","    os.chdir(\"/content/gdrive/MyDrive/NFL_Challenge/NFL-GPT/NFL data\")"]},{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":215,"status":"ok","timestamp":1695750225368,"user":{"displayName":"sam Chain","userId":"00779398991030525753"},"user_tz":-120},"id":"B2pOQ6qWeILn","outputId":"7e91fa10-a10c-4681-e348-1d5fed9420b1"},"outputs":[{"data":{"text/plain":["['data_models',\n"," '.DS_Store',\n"," 'LICENSE',\n"," 'models',\n"," 'README.md',\n"," '.gitignore',\n"," '.gitattributes',\n"," 'data_preprocessing',\n"," 'index',\n"," '.git',\n"," 'notebooks']"]},"execution_count":3,"metadata":{},"output_type":"execute_result"}],"source":["os.listdir()"]},{"cell_type":"code","execution_count":4,"metadata":{"executionInfo":{"elapsed":6338,"status":"ok","timestamp":1695750238260,"user":{"displayName":"sam Chain","userId":"00779398991030525753"},"user_tz":-120},"id":"n21dB8fmlAi_"},"outputs":[{"name":"stderr","output_type":"stream","text":["[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:337] Error parsing text-format tensorflow.data.experimental.DistributedSnapshotMetadata: 1:1: Invalid control characters encountered in text.\n","[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:337] Error parsing text-format tensorflow.data.experimental.DistributedSnapshotMetadata: 1:3: Expected identifier, got: 6356410735955644020\n","[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:337] Error parsing text-format tensorflow.data.experimental.DistributedSnapshotMetadata: 1:1: Invalid control characters encountered in text.\n","[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:337] Error parsing text-format tensorflow.data.experimental.DistributedSnapshotMetadata: 1:3: Expected identifier, got: 8791739918326820233\n"]}],"source":["training_data = tf.data.Dataset.load(\"data_models/play_pred_binary/train_play_prediction_binary\")\n","testing_data = tf.data.Dataset.load(\"data_models/play_pred_binary/test_play_prediction_binary\")"]},{"cell_type":"code","execution_count":5,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":6,"status":"ok","timestamp":1695750241105,"user":{"displayName":"sam Chain","userId":"00779398991030525753"},"user_tz":-120},"id":"8D31HaTelyvO","outputId":"1d3697f5-a143-43a1-9ee9-413564503b82"},"outputs":[{"data":{"text/plain":["<_LoadDataset element_spec=({'def': {'OffDef': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'season_ID': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'position_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'down_ID': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'input_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'start_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'pos_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'Success': TensorSpec(shape=(), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'yard_ID': TensorSpec(shape=(), dtype=tf.int64, name=None), 'scrim_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'playId': TensorSpec(shape=(), dtype=tf.int64, name=None), 'gameId': TensorSpec(shape=(), dtype=tf.int64, name=None), 'token_type_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'team_ID': TensorSpec(shape=(11,), dtype=tf.int64, name=None)}, 'off': {'OffDef': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'season_ID': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'position_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'down_ID': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'input_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'start_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'pos_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'Success': TensorSpec(shape=(), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'yard_ID': TensorSpec(shape=(), dtype=tf.int64, name=None), 'scrim_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'playId': TensorSpec(shape=(), dtype=tf.int64, name=None), 'gameId': TensorSpec(shape=(), dtype=tf.int64, name=None), 'token_type_ids': TensorSpec(shape=(11,), dtype=tf.int64, name=None), 'team_ID': TensorSpec(shape=(11,), dtype=tf.int64, name=None)}}, TensorSpec(shape=(), dtype=tf.float64, name=None))>"]},"execution_count":5,"metadata":{},"output_type":"execute_result"}],"source":["training_data"]},{"cell_type":"code","execution_count":28,"metadata":{"id":"EHNS1yT0p5sM"},"outputs":[{"data":{"text/plain":["<tensorflow.python.checkpoint.checkpoint.CheckpointLoadStatus at 0x2a58d0a50>"]},"execution_count":28,"metadata":{},"output_type":"execute_result"}],"source":["from models.modeling.QBGPT.models import QBGPT, AttentionBlock\n","\n","moves_to_pred = 11164\n","input_size = 11166\n","starts_size = 1985\n","scrimmage_size = 100\n","positions_id = 29\n","temp_ids = 52\n","\n","\n","model_medium = QBGPT(input_vocab_size = input_size,\n","                    positional_vocab_size = temp_ids,\n","                    position_vocab_size=positions_id,\n","                    start_vocab_size=starts_size,\n","                    scrimmage_vocab_size=scrimmage_size,\n","                    offdef_vocab_size = 2,\n","                    type_vocab_size = 2,\n","                    playtype_vocab_size = 9,\n","                    embedding_dim = 256,\n","                    hidden_dim = 256,\n","                    to_pred_size = moves_to_pred)\n","\n","\n","\n","model_medium.load_weights(\"models/modeling/weights/QBGPT/model_medium/QBGPT\")"]},{"cell_type":"code","execution_count":35,"metadata":{},"outputs":[{"name":"stderr","output_type":"stream","text":["[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:337] Error parsing text-format tensorflow.data.experimental.DistributedSnapshotMetadata: 1:1: Invalid control characters encountered in text.\n","[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:337] Error parsing text-format tensorflow.data.experimental.DistributedSnapshotMetadata: 1:3: Expected identifier, got: 7493229832319264585\n"]}],"source":["test_data = tf.data.Dataset.load(\"data_models/QB-GPT/test_tokens_NFL_GPT\")\n","testing_data = test_data.batch(16)"]},{"cell_type":"code","execution_count":36,"metadata":{},"outputs":[{"name":"stderr","output_type":"stream","text":["[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:337] Error parsing text-format tensorflow.data.experimental.DistributedSnapshotMetadata: 1:1: Invalid control characters encountered in text.\n","[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:337] Error parsing text-format tensorflow.data.experimental.DistributedSnapshotMetadata: 1:3: Expected identifier, got: 7493229832319264585\n"]},{"ename":"InvalidArgumentError","evalue":"Graph execution error:\n\nDetected at node 'qbgpt_9/encoder_9/embedding_84/type_encoder_9/embedding_91/embedding_lookup' defined at (most recent call last):\n    File \"<frozen runpy>\", line 198, in _run_module_as_main\n    File \"<frozen runpy>\", line 88, in _run_code\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n      app.start()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n      self._run_once()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n      handle._run()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n      result = self._run_cell(\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n      result = runner(coro)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/ipykernel_84928/4145719064.py\", line 4, in <module>\n      preds = model_medium.predict(x)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2554, in predict\n      tmp_batch_outputs = self.predict_function(iterator)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2341, in predict_function\n      return step_function(self, iterator)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2327, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2315, in run_step\n      outputs = model.predict_step(data)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2283, in predict_step\n      return self(x, training=False)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 443, in call\n      encoded = self.Encoder(x)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 314, in call\n      embed = self.Embedding(x)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 154, in call\n      type_embed = self.TypeEmbedding(x)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 90, in call\n      embed = self.Embedding(x[\"token_type_ids\"])\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/layers/core/embedding.py\", line 272, in call\n      out = tf.nn.embedding_lookup(self.embeddings, inputs)\nNode: 'qbgpt_9/encoder_9/embedding_84/type_encoder_9/embedding_91/embedding_lookup'\nindices[15,177] = 3 is not in [0, 2)\n\t [[{{node qbgpt_9/encoder_9/embedding_84/type_encoder_9/embedding_91/embedding_lookup}}]] [Op:__inference_predict_function_2291]","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)","\u001b[1;32m/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb Cell 8\u001b[0m line \u001b[0;36m4\n\u001b[1;32m      <a href='vscode-notebook-cell:/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb#X25sZmlsZQ%3D%3D?line=1'>2</a>\u001b[0m predss \u001b[39m=\u001b[39m []\n\u001b[1;32m      <a href='vscode-notebook-cell:/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb#X25sZmlsZQ%3D%3D?line=2'>3</a>\u001b[0m \u001b[39mfor\u001b[39;00m x, y \u001b[39min\u001b[39;00m testing_data:\n\u001b[0;32m----> <a href='vscode-notebook-cell:/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb#X25sZmlsZQ%3D%3D?line=3'>4</a>\u001b[0m     preds \u001b[39m=\u001b[39m model_medium\u001b[39m.\u001b[39;49mpredict(x)\n\u001b[1;32m      <a href='vscode-notebook-cell:/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb#X25sZmlsZQ%3D%3D?line=4'>5</a>\u001b[0m     predss\u001b[39m.\u001b[39mappend(preds)\n\u001b[1;32m      <a href='vscode-notebook-cell:/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb#X25sZmlsZQ%3D%3D?line=6'>7</a>\u001b[0m     i\u001b[39m+\u001b[39m\u001b[39m=\u001b[39m\u001b[39m1\u001b[39m\n","File \u001b[0;32m~/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[39m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[39m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[39mdel\u001b[39;00m filtered_tb\n","File \u001b[0;32m~/anaconda3/envs/nflgpt/lib/python3.11/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[39m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[39m=\u001b[39m pywrap_tfe\u001b[39m.\u001b[39mTFE_Py_Execute(ctx\u001b[39m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[39mexcept\u001b[39;00m core\u001b[39m.\u001b[39m_NotOkStatusException \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[39mif\u001b[39;00m name \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n","\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node 'qbgpt_9/encoder_9/embedding_84/type_encoder_9/embedding_91/embedding_lookup' defined at (most recent call last):\n    File \"<frozen runpy>\", line 198, in _run_module_as_main\n    File \"<frozen runpy>\", line 88, in _run_code\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n      app.start()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n      self._run_once()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n      handle._run()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n      result = self._run_cell(\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n      result = runner(coro)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/ipykernel_84928/4145719064.py\", line 4, in <module>\n      preds = model_medium.predict(x)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2554, in predict\n      tmp_batch_outputs = self.predict_function(iterator)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2341, in predict_function\n      return step_function(self, iterator)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2327, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2315, in run_step\n      outputs = model.predict_step(data)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 2283, in predict_step\n      return self(x, training=False)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 443, in call\n      encoded = self.Encoder(x)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 314, in call\n      embed = self.Embedding(x)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 154, in call\n      type_embed = self.TypeEmbedding(x)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 90, in call\n      embed = self.Embedding(x[\"token_type_ids\"])\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/layers/core/embedding.py\", line 272, in call\n      out = tf.nn.embedding_lookup(self.embeddings, inputs)\nNode: 'qbgpt_9/encoder_9/embedding_84/type_encoder_9/embedding_91/embedding_lookup'\nindices[15,177] = 3 is not in [0, 2)\n\t [[{{node qbgpt_9/encoder_9/embedding_84/type_encoder_9/embedding_91/embedding_lookup}}]] [Op:__inference_predict_function_2291]"]}],"source":["i = 0\n","predss = []\n","for x, y in testing_data:\n","    preds = model_medium.predict(x)\n","    predss.append(preds)\n","    \n","    i+=1\n","    if i == 3:\n","        break"]},{"cell_type":"code","execution_count":29,"metadata":{},"outputs":[],"source":["class DownEncoder(tf.keras.Model):\n","  def __init__(self, vocab_size : int, embedding_dim : int):\n","        super(DownEncoder, self).__init__()\n","\n","        self.Embedding = tf.keras.layers.Embedding(input_dim = vocab_size,\n","                                                   output_dim = embedding_dim)\n","\n","  def call(self, x):\n","    embed = self.Embedding(x[\"down_id\"])\n","    return embed\n","\n","class SeasonEncoder(tf.keras.Model):\n","  def __init__(self, vocab_size : int, embedding_dim : int):\n","        super(SeasonEncoder, self).__init__()\n","\n","        self.Embedding = tf.keras.layers.Embedding(input_dim = vocab_size,\n","                                                   output_dim = embedding_dim)\n","\n","  def call(self, x):\n","    embed = self.Embedding(x[\"season_id\"])\n","    return embed\n","\n","class TeamEncoder(tf.keras.Model):\n","  def __init__(self, vocab_size : int, embedding_dim : int):\n","        super(TeamEncoder, self).__init__()\n","\n","        self.Embedding = tf.keras.layers.Embedding(input_dim = vocab_size,\n","                                                   output_dim = embedding_dim)\n","\n","  def call(self, x):\n","    embed = self.Embedding(x[\"team_id\"])\n","    return embed\n","\n","\n","class MetaEmbedding(tf.keras.Model):\n","  def __init__(self, \n","               team_vocab_size : int, \n","               season_vocab_size : int, \n","               down_vocab_size : int, \n","               embedding_dim : int):\n","        super(MetaEmbedding, self).__init__()\n","\n","        self.TeamEmbedding = TeamEncoder(vocab_size= team_vocab_size,\n","                                         embedding_dim=embedding_dim)\n","        self.SeasonEmbedding = SeasonEncoder(vocab_size= season_vocab_size,\n","                                         embedding_dim=embedding_dim)\n","        self.DownEmbedding = DownEncoder(vocab_size= down_vocab_size,\n","                                         embedding_dim=embedding_dim)\n","        \n","        self.Add = tf.keras.layers.Add()\n","        \n","        self.Dense = tf.keras.layers.Dense(embedding_dim, activation = \"gelu\")\n","\n","  def call(self, x):\n","    team_embed = self.TeamEmbedding(x)\n","    season_embed = self.SeasonEmbedding(x)\n","    down_embed = self.DownEmbedding(x)\n","    \n","    added = self.Add([team_embed, season_embed, down_embed])\n","    \n","    encoded = self.Dense(added)\n","    \n","    return encoded\n","\n","class Helenos(tf.keras.Model):\n","    def __init__(self, \n","                 team_vocab_size : int, \n","                season_vocab_size : int, \n","                down_vocab_size : int, \n","                embedding_dim : int,\n","                encoder : tf.keras.Model,\n","                to_pred : int,\n","                activation : str):\n","        super(Helenos, self).__init__()\n","        \n","        self.Encoder = encoder\n","        self.MetaEmbedding = MetaEmbedding(team_vocab_size=team_vocab_size,\n","                                           season_vocab_size=season_vocab_size,\n","                                           down_vocab_size=down_vocab_size,\n","                                           embedding_dim=embedding_dim)\n","        \n","        self.Add = tf.keras.layers.Add()\n","        \n","        self.Attention = AttentionBlock(num_heads=1,\n","                                        hidden_dim=256,\n","                                        output_dim=256)\n","        \n","        self.Dense = tf.keras.layers.Dense(256, activation = \"gelu\")\n","        \n","        self.Pred = tf.keras.layers.Dense(to_pred, activation = activation)\n","        \n","    \n","    def call(self, x):\n","        encoded_qb = self.Encoder(x)\n","        encoded_meta = self.MetaEmbedding(x)\n","        \n","        encoded = self.Add([encoded_qb, encoded_meta])\n","        \n","        logits = self.Attention(encoded)\n","        \n","        densed = self.Dense(logits)\n","        \n","        preds = self.Pred(densed)\n","        \n","        return preds"]},{"cell_type":"code","execution_count":31,"metadata":{},"outputs":[],"source":["model = Helenos(team_vocab_size=32,\n","                season_vocab_size= 6,\n","                down_vocab_size= 5,\n","                embedding_dim= 256,\n","                encoder = model_medium.Encoder,\n","                to_pred=1,\n","                activation= \"sigmoid\")"]},{"cell_type":"code","execution_count":32,"metadata":{},"outputs":[{"name":"stderr","output_type":"stream","text":["WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.\n","WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.\n"]},{"name":"stdout","output_type":"stream","text":["Epoch 1/2\n","WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n"]},{"name":"stderr","output_type":"stream","text":["[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:337] Error parsing text-format tensorflow.data.experimental.DistributedSnapshotMetadata: 1:1: Invalid control characters encountered in text.\n","[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:337] Error parsing text-format tensorflow.data.experimental.DistributedSnapshotMetadata: 1:3: Expected identifier, got: 6356410735955644020\n","WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Logits.kernel\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Logits.kernel\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Logits.bias\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Logits.bias\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._iterations\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._iterations\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._learning_rate\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._learning_rate\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.DenseHead.kernel\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.DenseHead.kernel\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.DenseHead.bias\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.DenseHead.bias\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.1\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.1\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.2\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.2\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.3\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.3\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.4\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.4\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.5\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.5\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.6\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.6\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.7\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.7\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.8\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.8\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.9\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.9\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.10\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.10\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.11\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.11\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.12\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.12\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.13\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.13\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.14\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.14\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.15\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.15\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.16\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.16\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.17\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.17\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.18\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.18\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.19\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.19\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.20\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.20\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.21\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.21\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.22\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.22\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.23\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.23\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.24\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.24\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.25\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.25\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.26\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.26\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.27\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.27\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.28\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.28\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.29\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.29\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.30\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.30\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.31\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.31\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.32\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.32\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.33\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.33\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.34\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.34\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.35\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.35\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.36\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.36\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.37\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.37\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.38\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.38\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.39\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.39\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.40\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.40\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.41\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.41\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.42\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.42\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.43\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.43\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.44\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.44\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.45\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.45\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.46\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.46\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.47\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.47\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.48\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer._variables.48\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.Dense.kernel\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.Dense.kernel\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.Dense.bias\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.Dense.bias\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Query.kernel\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Query.kernel\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Query.bias\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Query.bias\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Key.kernel\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Key.kernel\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Key.bias\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Key.bias\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Value.kernel\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Value.kernel\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Value.bias\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Value.bias\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Dense.kernel\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Dense.kernel\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Dense.bias\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Dense.bias\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Norm.gamma\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Norm.gamma\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Norm.beta\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Norm.beta\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Norm.moving_mean\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Norm.moving_mean\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Norm.moving_variance\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Attention1.Norm.moving_variance\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.InputEmbedding.Embedding.embeddings\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.InputEmbedding.Embedding.embeddings\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.PositionalEmbedding.Embedding.embeddings\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.PositionalEmbedding.Embedding.embeddings\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.PositionEmbedding.Embedding.embeddings\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.PositionEmbedding.Embedding.embeddings\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.ScrimEmbedding.Embedding.embeddings\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.ScrimEmbedding.Embedding.embeddings\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.StartEmbedding.Embedding.embeddings\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.StartEmbedding.Embedding.embeddings\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.OffDefEmbedding.Embedding.embeddings\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.OffDefEmbedding.Embedding.embeddings\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.TypeEmbedding.Embedding.embeddings\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.TypeEmbedding.Embedding.embeddings\n"]},{"name":"stdout","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.PlayTypeEmbedding.Embedding.embeddings\n"]},{"name":"stderr","output_type":"stream","text":["WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).Encoder.Embedding.PlayTypeEmbedding.Embedding.embeddings\n"]},{"ename":"RuntimeError","evalue":"in user code:\n\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1338, in train_function  *\n        return step_function(self, iterator)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1322, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1303, in run_step  **\n        outputs = model.train_step(data)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1080, in train_step\n        y_pred = self(x, training=True)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filehinfywmy.py\", line 10, in tf__call\n        encoded_qb = ag__.converted_call(ag__.ld(self).Encoder, (ag__.ld(x),), None, fscope)\n    File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileohpk6a1f.py\", line 10, in tf__call\n        embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x),), None, fscope)\n    File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileiid2er82.py\", line 10, in tf__call\n        input_embed = ag__.converted_call(ag__.ld(self).InputEmbedding, (ag__.ld(x),), None, fscope)\n    File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filetldm2xpd.py\", line 10, in tf__call\n        embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x)['input_ids'],), None, fscope)\n\n    RuntimeError: Exception encountered when calling layer 'helenos_2' (type Helenos).\n    \n    in user code:\n    \n        File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/ipykernel_84928/2517353970.py\", line 94, in call  *\n            encoded_qb = self.Encoder(x)\n        File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler  **\n            raise e.with_traceback(filtered_tb) from None\n        File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileohpk6a1f.py\", line 10, in tf__call\n            embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x),), None, fscope)\n        File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileiid2er82.py\", line 10, in tf__call\n            input_embed = ag__.converted_call(ag__.ld(self).InputEmbedding, (ag__.ld(x),), None, fscope)\n        File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filetldm2xpd.py\", line 10, in tf__call\n            embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x)['input_ids'],), None, fscope)\n    \n        RuntimeError: Exception encountered when calling layer 'encoder_9' (type Encoder).\n        \n        in user code:\n        \n            File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 314, in call  *\n                embed = self.Embedding(x)\n            File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler  **\n                raise e.with_traceback(filtered_tb) from None\n            File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileiid2er82.py\", line 10, in tf__call\n                input_embed = ag__.converted_call(ag__.ld(self).InputEmbedding, (ag__.ld(x),), None, fscope)\n            File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filetldm2xpd.py\", line 10, in tf__call\n                embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x)['input_ids'],), None, fscope)\n        \n            RuntimeError: Exception encountered when calling layer 'embedding_84' (type Embedding).\n            \n            in user code:\n            \n                File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 149, in call  *\n                    input_embed = self.InputEmbedding(x)\n                File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler  **\n                    raise e.with_traceback(filtered_tb) from None\n                File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filetldm2xpd.py\", line 10, in tf__call\n                    embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x)['input_ids'],), None, fscope)\n            \n                RuntimeError: Exception encountered when calling layer 'input_encoder_9' (type InputEncoder).\n                \n                KeyError: 'input_ids'\n                \n                Call arguments received by layer 'input_encoder_9' (type InputEncoder):\n                  • x={'def': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}, 'off': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}}\n            \n            \n            Call arguments received by layer 'embedding_84' (type Embedding):\n              • x={'def': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}, 'off': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}}\n        \n        \n        Call arguments received by layer 'encoder_9' (type Encoder):\n          • x={'def': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}, 'off': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}}\n    \n    \n    Call arguments received by layer 'helenos_2' (type Helenos):\n      • x={'def': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}, 'off': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}}\n","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)","\u001b[1;32m/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb Cell 9\u001b[0m line \u001b[0;36m6\n\u001b[1;32m      <a href='vscode-notebook-cell:/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb#X20sZmlsZQ%3D%3D?line=0'>1</a>\u001b[0m model\u001b[39m.\u001b[39mcompile(optimizer\u001b[39m=\u001b[39mtf\u001b[39m.\u001b[39mkeras\u001b[39m.\u001b[39moptimizers\u001b[39m.\u001b[39mAdam(),\n\u001b[1;32m      <a href='vscode-notebook-cell:/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb#X20sZmlsZQ%3D%3D?line=1'>2</a>\u001b[0m                     loss\u001b[39m=\u001b[39m tf\u001b[39m.\u001b[39mkeras\u001b[39m.\u001b[39mlosses\u001b[39m.\u001b[39mBinaryCrossentropy(),\n\u001b[1;32m      <a href='vscode-notebook-cell:/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb#X20sZmlsZQ%3D%3D?line=2'>3</a>\u001b[0m                     metrics\u001b[39m=\u001b[39m[tf\u001b[39m.\u001b[39mkeras\u001b[39m.\u001b[39mmetrics\u001b[39m.\u001b[39mAccuracy(),\n\u001b[1;32m      <a href='vscode-notebook-cell:/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb#X20sZmlsZQ%3D%3D?line=3'>4</a>\u001b[0m                              tf\u001b[39m.\u001b[39mkeras\u001b[39m.\u001b[39mmetrics\u001b[39m.\u001b[39mAUC()])\n\u001b[0;32m----> <a href='vscode-notebook-cell:/Users/samuel/Documents/GitHub/QB-GPT/notebooks/Helenos/2_play_predictions.ipynb#X20sZmlsZQ%3D%3D?line=5'>6</a>\u001b[0m history_small \u001b[39m=\u001b[39m model\u001b[39m.\u001b[39;49mfit(training_data, validation_data \u001b[39m=\u001b[39;49m testing_data, epochs\u001b[39m=\u001b[39;49m\u001b[39m2\u001b[39;49m)\n","File \u001b[0;32m~/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[39m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[39m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[39mdel\u001b[39;00m filtered_tb\n","File \u001b[0;32m/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileophrnioq.py:15\u001b[0m, in \u001b[0;36mouter_factory.<locals>.inner_factory.<locals>.tf__train_function\u001b[0;34m(iterator)\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m     14\u001b[0m     do_return \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[0;32m---> 15\u001b[0m     retval_ \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(step_function), (ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m), ag__\u001b[39m.\u001b[39mld(iterator)), \u001b[39mNone\u001b[39;00m, fscope)\n\u001b[1;32m     16\u001b[0m \u001b[39mexcept\u001b[39;00m:\n\u001b[1;32m     17\u001b[0m     do_return \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n","File \u001b[0;32m/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filehinfywmy.py:10\u001b[0m, in \u001b[0;36mouter_factory.<locals>.inner_factory.<locals>.tf__call\u001b[0;34m(self, x)\u001b[0m\n\u001b[1;32m      8\u001b[0m do_return \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n\u001b[1;32m      9\u001b[0m retval_ \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mUndefinedReturnValue()\n\u001b[0;32m---> 10\u001b[0m encoded_qb \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39;49mconverted_call(ag__\u001b[39m.\u001b[39;49mld(\u001b[39mself\u001b[39;49m)\u001b[39m.\u001b[39;49mEncoder, (ag__\u001b[39m.\u001b[39;49mld(x),), \u001b[39mNone\u001b[39;49;00m, fscope)\n\u001b[1;32m     11\u001b[0m encoded_meta \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m)\u001b[39m.\u001b[39mMetaEmbedding, (ag__\u001b[39m.\u001b[39mld(x),), \u001b[39mNone\u001b[39;00m, fscope)\n\u001b[1;32m     12\u001b[0m encoded \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m)\u001b[39m.\u001b[39mAdd, ([ag__\u001b[39m.\u001b[39mld(encoded_qb), ag__\u001b[39m.\u001b[39mld(encoded_meta)],), \u001b[39mNone\u001b[39;00m, fscope)\n","File \u001b[0;32m/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileohpk6a1f.py:10\u001b[0m, in \u001b[0;36mouter_factory.<locals>.inner_factory.<locals>.tf__call\u001b[0;34m(self, x)\u001b[0m\n\u001b[1;32m      8\u001b[0m do_return \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n\u001b[1;32m      9\u001b[0m retval_ \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mUndefinedReturnValue()\n\u001b[0;32m---> 10\u001b[0m embed \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39;49mconverted_call(ag__\u001b[39m.\u001b[39;49mld(\u001b[39mself\u001b[39;49m)\u001b[39m.\u001b[39;49mEmbedding, (ag__\u001b[39m.\u001b[39;49mld(x),), \u001b[39mNone\u001b[39;49;00m, fscope)\n\u001b[1;32m     11\u001b[0m h1 \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m)\u001b[39m.\u001b[39mAttention1, (ag__\u001b[39m.\u001b[39mld(embed), ag__\u001b[39m.\u001b[39mld(x)[\u001b[39m'\u001b[39m\u001b[39mpos_ids\u001b[39m\u001b[39m'\u001b[39m], ag__\u001b[39m.\u001b[39mld(x)[\u001b[39m'\u001b[39m\u001b[39mattention_mask\u001b[39m\u001b[39m'\u001b[39m]), \u001b[39mNone\u001b[39;00m, fscope)\n\u001b[1;32m     12\u001b[0m encoded \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m)\u001b[39m.\u001b[39mDenseHead, (ag__\u001b[39m.\u001b[39mld(h1),), \u001b[39mNone\u001b[39;00m, fscope)\n","File \u001b[0;32m/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileiid2er82.py:10\u001b[0m, in \u001b[0;36mouter_factory.<locals>.inner_factory.<locals>.tf__call\u001b[0;34m(self, x)\u001b[0m\n\u001b[1;32m      8\u001b[0m do_return \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n\u001b[1;32m      9\u001b[0m retval_ \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mUndefinedReturnValue()\n\u001b[0;32m---> 10\u001b[0m input_embed \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39;49mconverted_call(ag__\u001b[39m.\u001b[39;49mld(\u001b[39mself\u001b[39;49m)\u001b[39m.\u001b[39;49mInputEmbedding, (ag__\u001b[39m.\u001b[39;49mld(x),), \u001b[39mNone\u001b[39;49;00m, fscope)\n\u001b[1;32m     11\u001b[0m positional_embed \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m)\u001b[39m.\u001b[39mPositionalEmbedding, (ag__\u001b[39m.\u001b[39mld(x),), \u001b[39mNone\u001b[39;00m, fscope)\n\u001b[1;32m     12\u001b[0m position_embed \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m)\u001b[39m.\u001b[39mPositionEmbedding, (ag__\u001b[39m.\u001b[39mld(x),), \u001b[39mNone\u001b[39;00m, fscope)\n","File \u001b[0;32m/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filetldm2xpd.py:10\u001b[0m, in \u001b[0;36mouter_factory.<locals>.inner_factory.<locals>.tf__call\u001b[0;34m(self, x)\u001b[0m\n\u001b[1;32m      8\u001b[0m do_return \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n\u001b[1;32m      9\u001b[0m retval_ \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mUndefinedReturnValue()\n\u001b[0;32m---> 10\u001b[0m embed \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m)\u001b[39m.\u001b[39mEmbedding, (ag__\u001b[39m.\u001b[39;49mld(x)[\u001b[39m'\u001b[39;49m\u001b[39minput_ids\u001b[39;49m\u001b[39m'\u001b[39;49m],), \u001b[39mNone\u001b[39;00m, fscope)\n\u001b[1;32m     11\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m     12\u001b[0m     do_return \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n","\u001b[0;31mRuntimeError\u001b[0m: in user code:\n\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1338, in train_function  *\n        return step_function(self, iterator)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1322, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1303, in run_step  **\n        outputs = model.train_step(data)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1080, in train_step\n        y_pred = self(x, training=True)\n    File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filehinfywmy.py\", line 10, in tf__call\n        encoded_qb = ag__.converted_call(ag__.ld(self).Encoder, (ag__.ld(x),), None, fscope)\n    File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileohpk6a1f.py\", line 10, in tf__call\n        embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x),), None, fscope)\n    File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileiid2er82.py\", line 10, in tf__call\n        input_embed = ag__.converted_call(ag__.ld(self).InputEmbedding, (ag__.ld(x),), None, fscope)\n    File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filetldm2xpd.py\", line 10, in tf__call\n        embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x)['input_ids'],), None, fscope)\n\n    RuntimeError: Exception encountered when calling layer 'helenos_2' (type Helenos).\n    \n    in user code:\n    \n        File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/ipykernel_84928/2517353970.py\", line 94, in call  *\n            encoded_qb = self.Encoder(x)\n        File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler  **\n            raise e.with_traceback(filtered_tb) from None\n        File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileohpk6a1f.py\", line 10, in tf__call\n            embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x),), None, fscope)\n        File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileiid2er82.py\", line 10, in tf__call\n            input_embed = ag__.converted_call(ag__.ld(self).InputEmbedding, (ag__.ld(x),), None, fscope)\n        File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filetldm2xpd.py\", line 10, in tf__call\n            embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x)['input_ids'],), None, fscope)\n    \n        RuntimeError: Exception encountered when calling layer 'encoder_9' (type Encoder).\n        \n        in user code:\n        \n            File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 314, in call  *\n                embed = self.Embedding(x)\n            File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler  **\n                raise e.with_traceback(filtered_tb) from None\n            File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_fileiid2er82.py\", line 10, in tf__call\n                input_embed = ag__.converted_call(ag__.ld(self).InputEmbedding, (ag__.ld(x),), None, fscope)\n            File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filetldm2xpd.py\", line 10, in tf__call\n                embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x)['input_ids'],), None, fscope)\n        \n            RuntimeError: Exception encountered when calling layer 'embedding_84' (type Embedding).\n            \n            in user code:\n            \n                File \"/Users/samuel/Documents/GitHub/QB-GPT/models/modeling/QBGPT/models.py\", line 149, in call  *\n                    input_embed = self.InputEmbedding(x)\n                File \"/Users/samuel/anaconda3/envs/nflgpt/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler  **\n                    raise e.with_traceback(filtered_tb) from None\n                File \"/var/folders/xc/clt_qlgj3cncjzx754k5yw_c0000gn/T/__autograph_generated_filetldm2xpd.py\", line 10, in tf__call\n                    embed = ag__.converted_call(ag__.ld(self).Embedding, (ag__.ld(x)['input_ids'],), None, fscope)\n            \n                RuntimeError: Exception encountered when calling layer 'input_encoder_9' (type InputEncoder).\n                \n                KeyError: 'input_ids'\n                \n                Call arguments received by layer 'input_encoder_9' (type InputEncoder):\n                  • x={'def': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}, 'off': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}}\n            \n            \n            Call arguments received by layer 'embedding_84' (type Embedding):\n              • x={'def': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}, 'off': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}}\n        \n        \n        Call arguments received by layer 'encoder_9' (type Encoder):\n          • x={'def': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}, 'off': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}}\n    \n    \n    Call arguments received by layer 'helenos_2' (type Helenos):\n      • x={'def': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}, 'off': {'OffDef': 'tf.Tensor(shape=(11,), dtype=int64)', 'season_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'position_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'down_ID': 'tf.Tensor(shape=(11,), dtype=int64)', 'input_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'start_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'pos_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'Success': 'tf.Tensor(shape=(), dtype=float32)', 'attention_mask': 'tf.Tensor(shape=(11,), dtype=int64)', 'yard_ID': 'tf.Tensor(shape=(), dtype=int64)', 'scrim_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'playId': 'tf.Tensor(shape=(), dtype=int64)', 'gameId': 'tf.Tensor(shape=(), dtype=int64)', 'token_type_ids': 'tf.Tensor(shape=(11,), dtype=int64)', 'team_ID': 'tf.Tensor(shape=(11,), dtype=int64)'}}\n"]}],"source":["model.compile(optimizer=tf.keras.optimizers.Adam(),\n","                    loss= tf.keras.losses.BinaryCrossentropy(),\n","                    metrics=[tf.keras.metrics.Accuracy(),\n","                             tf.keras.metrics.AUC()])\n","\n","history_small = model.fit(training_data, validation_data = testing_data, epochs=2)"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":[]}],"metadata":{"accelerator":"GPU","colab":{"authorship_tag":"ABX9TyOdfJoNF73jOSn/+XfcVm3w","gpuType":"T4","provenance":[]},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.4"}},"nbformat":4,"nbformat_minor":0}
